# -*- coding: utf-8 -*-
"""cse111 assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11gyvcFH9ytqfBJfCXYJboUaNX4CqcRPh
"""

#task1 string
var = "HOusE"
upper=0
lower = 0
for i in var:
    if chr(65)<=i<=chr(90):
        upper+=1
    elif chr(97)<=i<=chr(122):
        lower+=1
if upper>lower:
    var=var.upper()
elif upper<=lower:
    var=var.lower()
print(var)

#task2 string
var = input()
len=len(var)
number=0
mix=0
word=0
for i in var:
  if chr(47)<=i<=chr(57):
    number+=1
  elif chr(65)<=i<=chr(90) or chr(97)<=i<=chr(122):
    word+=1
  else:
    mix+=1
if number==len:
  print("NUMBER")
elif word==len:
  print("WORD")
elif mix==len:
  print("MIXED")

#task3 string
var=input()
count=0
s=""
for i in var:
  if(count==2):
    break
  if 65<=ord(i)<=90:
    count+=1
  if count==1 and 97<=ord(i)<=122:
    s+=i
if len(s)==0:
  print("blank")
else:
  print(s)

#task4 string
var1,var2= input().split(", ")
st=""
count=0
for i in var1:
    if i in var2 :
      st+=i
for i in var2:
    if i in var1 :
      st+=i
if len(st)==0:
  print("Nothing in common")
print(st)

#task5 string
var=input()
a=0
b=0
c=0
d=0
for  i in var:
  if ord("A")<=ord(i)<=ord("Z"):
    a+=1
  elif ord("a")<=ord(i)<=ord("z") :
    b+=1
  elif ord("0")<=ord(i)<= ord("9"):
    c+=1
  else:
    d+=1
ch=""
if a!=0 and b!=0 and c!=0 and d!=0:
  print("OK")
if b==0:
  ch+="Lowercase Missing,"
if a==0:
  ch+= "Uppercase character Missing,"
if c==0:
  ch+="Digit missing"
if d==0:
  ch+= ",Special character missing"
if ch!="":
  print(ch)

#task1 list
my_lst = []
while True:
  asd = input()
  if asd.lower()=="stop":
    break
  else:
    my_lst.append(int(asd))
for i in my_lst:
  var1 = my_lst.count(i)
  print(f"{i} - {var1} times")

#task2 list
n=int(input())
max=-99999
maxlst=[]
for i in range(n):
  num=input().split(" ")
  sum=0
  for i in num:
    sum+=int(i)
  if sum>max:
    max=sum
    maxlst=num
print(max)
maxl = []
for i in maxlst:
  maxl.append(int(i))
print(maxl)

#task3
mylst = []
num=input()
if num!="STOP":
  num=num.split(" ")
  for i in num:
    mylst.append(int(i))
  mylst.sort(reverse=True)
  sum=0
  a=True
  for j in mylst:
    sum1=sum-j
    sum=j
    if sum1==1:
      a=True
    else:
      a=False
    sum1=0
  if a==True:
    print("UB Jumper")
  elif a==False:
    print("Not UB Jumper")

# Task5
var=input("Enter the value of n and k: ")
mylst=var.split(" ")

list_n=[]
a=input("Enter the number: ").split(" ")
for j in a:
  list_n.append(int(j))
sum=0
for i in list_n:
  if i+int(mylst[1])<5:
    sum+=1
print(sum//3)

#task5
member,times = tuple(int(num) for num in input().split())
data = [int(i) for i in input().split()]
while len(data)!= member:
  print("Member count and member participation data doesn't match.Please enter member participation data again")
  data = [int(i)for i in input().split()]
approved = [int(i) for i in data if (if times<=5)]
appr = len(approved)
if appr<3:
  print(0)
else:
  if appr%3==0:
    print(appr//3)
  elif (appr-1)%3 ==0:
    print((appr-1)//3)
  elif (appr-2)%3==0:
    print((appr-2)//3)

n_k_str=input("Enter the value of n and k: ")
n_k_list=n_k_str.split(" ")

list_n=[]
for i in range(1,int(n_k_list[0])+1):
  a=int(input("Enter the number: "))
  list_n.append(a)

sum=0
for i in list_n:
  if i+int(n_k_list[1])<5:
    sum+=1
print(sum//3)

"""dictionary

"""

#task 2 dictionary
my_list = []

inp = input()

while inp.lower() != "stop":

   my_list.append(int(inp))

   inp = input()

Dict_freq = {}

for i in my_list:

   if (i in Dict_freq):

       Dict_freq[i]+= 1

   else:

       Dict_freq[i] = 1

for key, value in Dict_freq.items():

   print (key,"-",value,"times")

#task1
var = {"a":100,"b":100,"c":200,"d":300},{"a":300,"b": 200,"d": 400,"e": 200}
dic1 = (var[0])
dic2 = var[1]
new = {}
for i in dic1:
  if i in dic2:
    value = dic1[i]+dic2[i]
    new[i]=value
  else:
    new[i]=dic1[i]

for i in dic2:
  if i not in new:
    new[i]=dic2[i]
print(new)
a=[]
for i in new.values():
  if i not in a:
    a.append(i)
a.sort()
print("values:",tuple(a))

#task2
frequency = {}

while True:
    num = input("Enter a number (or 'STOP' to stop): ")
    if num == "STOP":
        break
    if num.isdigit():
        if num in frequency:
            frequency[num] += 1
        else:
            frequency[num] = 1
for num, count in frequency.items():
    print(num, ":", count)

#task3
word,di=input(),{}
list1=word.split(',')
for i in list1:
  a=(i.strip()).split(':')
  value,key=a
  value1,key1=value.strip(),key.strip()
  if key1 not in list(di.keys()):
    di[key1]=[value1]
  else:
    di[key1].append(value1)
print(di)

#task4
di={'1':'.,?!:','2':'ABC','3':'DEF','4':'GHI','5':'JKL','6':'MNO','7':'PQRS','8':'TUV','9':'WXYZ','0':' '}
word,z=(input()).upper(),''
list1=list(di.values())
list2=list(di.keys())
for i in word:
  a=-1
  for j in list1:
    a+=1
    if i in j:
      z=str(list2[a])
      count=0
      for co in j:
        count+=1
        if co==i:
          z*=count
      print(z,end='')

#task1
word1='a: 100, b: 100, c: 200, d: 300'
word2='a: 300, b: 200, d: 400, e: 200'
li1=word1.split(',')
li2=word2.split(',')
di1,di2,di3={},{},{}
for i in li1:
  a,b=(i.strip()).split(':')
  di1[a.strip()]=int(b.strip())
for i in li2:
  a,b=(i.strip()).split(':')
  di2[a.strip()]=int(b.strip())
list1,list2,list3=list(di1.keys()),list(di2.keys()),[]
x=list2.copy()
for i in list1:
  if i not in list2:
    list2.append(i)
list2.sort()
for i in list2:
  if i in list1 and i in x:
    di3[i]=di1[i]+di2[i]
  elif i in list1:
    di3[i]=di1[i]
  else:
    di3[i]=di2[i]

for i in list(di3.values()):
  if i not in list3:
    list3.append(i)
list3.sort()
print(di3)
print(f'Values: {tuple(list3)}')