# -*- coding: utf-8 -*-
"""cse111 assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SbBgnTaDktggeER00eFHxqZWu4OuEkP
"""

#task1
def func(num1,num2):
  if num1==0 or num2==0:
    return 0
  else:
    result=(num1/num2)-(num1//num2)
    return result

func(int(input()),int(input()))

#task2
def func(var,var2):
  BMI = var2/((var/100)**2)
  if BMI<18.5:
    print(f"Score is {(BMI):.1f} You are underweight")
  elif 18.5<=BMI<=24.9:
    print(f"Score is {(BMI):.1f} You are Normal")
  elif 25 <=BMI<=30:
    print(f"Score is {(BMI):.1f} You are Overweight")
  elif BMI>30:
    print(f"Score is {(BMI):.1f} You are Obese")

func(float(input("height:")),float(input("weight:")))

#task3
def function(min,max,div):
  sum=0
  for i in range(min,max):
    if i%div==0:
      sum+=i
  print(sum)

function(3,16,3)

#task4
def order(name,place="Mohakhali"):
  if name=="BBQ Chicken Cheese Burger":
    item_price=250
  elif name=="Beef burger":
    item_price=170
  elif name=="Naga Drums":
    item_price=200

  if place=="Mohakhali" or place=="":
    delivery = 40
  else:
    delivery = 60

  return item_price+delivery+(8*item_price/100)


print(order(input(),input()))

#task5
def replace_domain(email,new_domain,old_domain="kaaj.com"):
  l = email.split("@")
  new_address = l[0]
  if l[1]==new_domain:
    print(f"Unchanged: {email}")
  else:
    print(f"changed: {l[0]}@{new_domain}")

replace_domain("alice@kaaj.com","sheba.xyz","kaaj.com")

#task6
def v_count(name):
  temp =[]
  v_text =""
  for i in name:
    if i in "AEIOUaeiou":
      temp.append(i)
  for i in range(len(temp)):
    if i==len(temp)-1:
      v_text+=temp[i]
    else:
      v_text+=temp[i]+", "
  if len(temp==0):
    print("No vowels in the name")
  else:
    print(f"Vowels: {v_text}. Total number of vowels: {len(temp)}")

v_count("Steve Jobs")

#task7
def func(a):
  p = True
  st = 0
  end=-1
  m_s=""
  for j in a:
    if j==" ":
      continue
    else:
      m_s+=j
  #for loop for modified string
  for i in range(0,len(m_s)//2):
      if (m_s[st]!= m_s[end]):
        p=False
        break
  if p==True:
    print("Palindrome")
  else:
    print("Not a Palindrome")

func(input())

#task8
def year(age):
  years = age//365
  sum=age%365
  months = sum//30
  days = sum%30
  print(f"{years} years, {months} months and {days} days")

year(int(input()))

#task-9
def correct(x):
  new_st=x[0].upper()
  for i in range(1,len(x)):

    l=[".","!","?"]

    if x[i-2] in l:
      new_st+=x[i].upper()
    elif x[i-1]==" " and x[i]=='i' and x[i+1]==" ":
      new_st+="I"
    else:
      new_st+=x[i]
  return new_st

print(correct("my favourite animal is a dog.a dog has sharp teeth so that it can eat flesh very easily. do you know my pet dog's name? i love my pet very much."))